### ISSUE TITLE
Flow Support

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/manta-style#30]
This issue is used to track the Flow Type support in manta-style

-------

- [ ] Flow Type Syntax
  - [x] `$Keys`
  - [x] `$Values`
  - [x] `$PropertyType`
  - [x] `$Shape<T>`
  - [x] `$ReadOnly<T>`
  - [x] `$Exact<T>`
  - [x] `$Diff<A, B>`
  - [x] `$Rest<A, B>`
  - [x] `$NonMaybeType<T>`
  - [x] `Array<T>`
  - [ ] `Existential Type (*)`
  - [ ] [Opaque Types](https://flow.org/en/docs/types/opaque-types/)
  - [ ] Function Types
    - [ ] `$ObjMap`
    - [ ] `$TupleMap`
    - [ ] `$Call`

- [ ] Flow Files dependency resolver - this is to transform not just the config file, but also the dependencies of config file. this is done automatically by typescript compiler but not flow babel transformer

**Comment by Cryrivers** [comment]
Will close this once annotation support lands on flowtype builder

**Comment by Cryrivers** [comment]
🎉

**Comment by tanhauhau** [comment]
🎉
