### ISSUE TITLE
Need to install globally?

### ISSUE THREAD

**Issue by wgao19** [Cryrivers/manta-style#54]
I installed 
```
npm install --save-dev @manta-style/cli @manta-style/plugin-builder-typescript @manta-style/plugin-mock-example
```
to project only and it doesn't work.
Reports no `ms` command found.
I had to install the `cli` globally for it to work.

**Comment by JennieJi** [comment]
no leh, just install @manta-style/cli, you should be able to find ms file in `node_modules/.bin/` and you can do `yarn ms ...`.

**Comment by wgao19** [comment]
My machine might be problematic, but have anyone of you encountered this error while installing the cli?
```
error An unexpected error occurred: "Running this command will add the dependency to the workspace root rather than workspace itself, which might not be what you want - if you really meant it, │spawn ssh-add /Users/gaow/.ssh/wgao19_rsa
make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).".
```
I never saw this with other libraries, though.

**Comment by wgao19** [comment]
I actually also encountered the problem where it complains I did not add `@manta-style/core`, should add this manually as well?

**Comment by JennieJi** [comment]
Wait, are u trying to add gitbook on root?

**Comment by wgao19** [comment]
No, I haven't worked on gitbook hook yet.

**Comment by tanhauhau** [comment]
> error An unexpected error occurred: "Running this command will add the dependency to the workspace root rather than workspace itself, which might not be what you want - if you really meant it, │spawn ssh-add /Users/gaow/.ssh/wgao19_rsa
make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).".

@wgao19 where did you see this error? you adding a dependency in the root folder of manta style?

**Comment by wgao19** [comment]
> @wgao19 where did you see this error? you adding a dependency in the root folder of manta style?

@tanhauhau Yes I saw this error when I tried to add in root folder by running `yarn add -D @manta-style/cli`

**Comment by Cryrivers** [comment]
as discussed in MM, we shouldn't allow users to install `@manta-style/cli` globally. because:
- our plugin discovery cannot discover global plugins
- global plugins installed might not have the plugin that a config file requires

for installation, sorry, the `cli` with latest architecture is only prereleased. you might have to run:
```
yarn add -D @manta-style/cli@0.2.0-alpha.2
```

**Comment by Cryrivers** [comment]
for gitbook thing, we need to make sure all our mock plugins, transformer, core packages support to run on both Node and browsers.

**Comment by wgao19** [comment]
@Cryrivers I see, thanks for clarifying. It will still take a while to complete the docs I think. If by the time the docs are ready but pending some minor fixes, we can always put a link to the issue. Will close this ticket for now. We can clean things up later (hopefully before next release) :P

**Comment by Cryrivers** [comment]
> why did you want to install @manta-style/cli in the root folder?
@wgao19 oh btw if you want to use manta style in `manta-style` repo, you have to create a new package under `packages` folder, and let `lerna` do the linking work. by right you cannot install them in root.
