### ISSUE TITLE
Deprecate `flowtype-helpers-type` and `typescript-helpers-type`

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/manta-style#55]
@tanhauhau

I feel the data in those packages is very unlikely to be shared. So could we make `test-helper` extract those information into `flowtype-helpers` and `typescript-helpers` directly and remove those packages?

**Comment by tanhauhau** [comment]
That was my initial intention.. but I dunno how to import them

**Comment by Cryrivers** [comment]
Fixed by #58
