### ISSUE TITLE
Mock image(s) of specific dimensions

### ISSUE THREAD

**Issue by wgao19** [Cryrivers/manta-style#61]
**Is your feature request related to a problem? Please describe.**
So that some image fields we can get an image of a right size.

**Describe the solution you'd like**

```
/**
 * @image ${keyword to search}
 * @width  ${width}
 * @height ${height}
 */
imageUrl: string;
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Cryrivers** [comment]
i'll add it in `@manta-style/helpers`, along with chaos monkey functions like `Delay`, `HTTPError`, etc.

**Comment by Cryrivers** [comment]
to elaborate more, this won't be a plugin, but a custom type.

**Comment by wgao19** [comment]
Nice. Looking forward.

**Comment by Cryrivers** [comment]
See #64
