### ISSUE TITLE
Help Wanted: Design a logo for manta-style

### ISSUE THREAD

**Issue by tanhauhau** [Cryrivers/manta-style#74]

**Comment by sr6033** [comment]
Have a look at #75 for the design.

**Comment by tanhauhau** [comment]
@Cryrivers what do you think?

**Comment by Cryrivers** [comment]
@sr6033 thanks for your contribution. could I have some additional modification on your creation?

**Comment by sr6033** [comment]
Sure. What else will you like?

**Comment by Cryrivers** [comment]
For the meaning of Manta Style, you might want to check out #1 . But I absolutely love the manta ray logo! So I'd like to keep the design, just re-coloring it, maybe adjusting the font a little bit as well.

**Comment by sr6033** [comment]
Okay sure. Right now I'm travelling. Once I reach, I will have a look at it. You can send me your mail id and I will mail you the updated logo over there before sending a PR.

**Comment by Cryrivers** [comment]
> Okay sure. Right now I'm travelling. In a day, I will have a look at it. You can send me your mail id and I will mail you the updated logo over there before sending a PR.

Thanks a lot. Could I derive a version from your creation?

**Comment by sr6033** [comment]
Yeah sure.

**Comment by sr6033** [comment]
@Cryrivers, your mail id?

**Comment by Cryrivers** [comment]
@sr6033 sorry for the late reply. mintytown@gmail.com
